version: '3'

output: prefixed

includes:
  test: Taskfile.test.yml

tasks:
  hook:setup:
    cmds:
      - git config core.hooksPath ./hooks

  hook:validate-go-changes:
    cmds:
      - task: test:unit

  run-ticker-example:
    cmds:
      - go run ./examples/ticker_job

  run-blocking-example:
    cmds:
      - go run ./examples/blocking_job
